name: build

# See: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#concurrency.
concurrency:
  group: ${{ github.head_ref }}-${{ github.workflow }}
  cancel-in-progress: true

on:
  pull_request:
    branches: "**"
    types:
      - opened
      - synchronize

  push:
    branches: "**" # XXX: Just for testing bh/ci - should be changed to 'main'.
    paths-ignore:
      - "configs/**"
      - "scripts/**"
      - ".envrc"
      - ".gitignore"
      - "LICENSE"
      - "**.md"

jobs:
  amazonka:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        ghc: [ghc961, ghc927]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
            extra-substituters = https://hydra.iohk.io
            experimental-features = nix-command flakes

      - uses: cachix/cachix-action@v12
        with:
          name: amazonka
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - uses: actions/checkout@v3

      - run: |
          nix develop --print-build-logs --command \
              bash -c 'cabal update && cabal freeze' '.#${{matrix.ghc}}'

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-

      - run: |
          nix develop --print-build-logs --command \
              bash -c 'cabal build amazonka-core amazonka' '.#${{matrix.ghc}}'

      - run: |
          nix develop --print-build-logs --command \
              bash -c 'cabal build all' '.#${{matrix.ghc}}'
